name: Public to development
on:
    push:
        branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github packages
        uses: docker/login-action@v3
        with:
          username: duncte123
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: oengusio/bot:dev
          cache-from: type=gha
          cache-to: type=gha
          build-args: |
            is_ci=true
            git_sha=${{ github.sha }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Trigger prod webhook
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.TESTING_WEBHOOK_URL }}
